/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArchiveCard: typeof import('./src/components/Archive/ArchiveCard.vue')['default']
    ArchiveCarousel: typeof import('./src/components/Archive/ArchiveCarousel.vue')['default']
    ArticleList: typeof import('./src/components/Home/ArticleList.vue')['default']
    Articles: typeof import('./src/components/Articles/Articles.vue')['default']
    Carousel: typeof import('./src/components/Home/Carousel.vue')['default']
    ClassifyList: typeof import('./src/components/Classify/ClassifyList.vue')['default']
    ElCarousel: typeof import('element-plus/es/el-carousel')['default']
    ElCarouselItem: typeof import('element-plus/es/el-carousel-item')['default']
    Footer: typeof import('./src/components/SideBar/Footer.vue')['default']
    GoTop: typeof import('./src/components/SideBar/goTop.vue')['default']
    IntroCard: typeof import('./src/components/Home/IntroCard.vue')['default']
    ListByClassify: typeof import('./src/components/Classify/ListByClassify.vue')['default']
    ListByTag: typeof import('./src/components/Tags/ListByTag.vue')['default']
    NavBar: typeof import('./src/components/SideBar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCloud: typeof import('./src/components/Home/TagCloud.vue')['default']
    Tags: typeof import('./src/components/Tags/TagsList.vue')['default']
    TagsCard: typeof import('./src/components/Tags/TagsList.vue')['default']
    TagsList: typeof import('./src/components/Tags/TagsList.vue')['default']
    TodoList: typeof import('./src/components/About/todoList.vue')['default']
    Waterfall: typeof import('./src/components/Photos/Waterfall.vue')['default']
  }
}
