/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArchiveBanner: typeof import('./src/components/Archive/ArchiveBanner.vue')['default']
    ArchiveCard: typeof import('./src/components/Archive/ArchiveCard.vue')['default']
    Carousel: typeof import('./src/components/Home/Carousel.vue')['default']
    ElCarousel: typeof import('element-plus/es/el-carousel')['default']
    ElCarouselItem: typeof import('element-plus/es/el-carousel-item')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GoTop: typeof import('./src/components/goTop.vue')['default']
    ImageGrid: typeof import('./src/components/Photos/ImageGrid.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PhotosBanner: typeof import('./src/components/Photos/PhotosBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsBanner: typeof import('./src/components/Tags/TagsBanner.vue')['default']
    TagsCard: typeof import('./src/components/Tags/TagsCard.vue')['default']
    TodoList: typeof import('./src/components/Home/todoList.vue')['default']
    ToHtml: typeof import('./src/components/Blog/toHtml.vue')['default']
    Waterfall: typeof import('./src/components/Photos/Waterfall.vue')['default']
  }
}
